Add missing include file
Fixes compile error with gcc 11, e.g.:

| ./include/mbgl/util/string.hpp:68:33: error: 'exception_ptr' in namespace
| 'std' does not name a type; did you mean 'exception'?
|    68 | std::string toString(const std::exception_ptr &);
|       |                                 ^~~~~~~~~~~~~
|       |                                 exception

%% original patch: 0005-Add-missing-include-file.patch